# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  About: /about
  rss: /atom.xml

menu_icon:
  Home: fa-home
  Archives: fa-archive
  Tag: fa-tag
  About: fa-user
  rss: fa-rss

# Content
excerpt_link: Read More

# Miscellaneous
favicon: /image/favicon.ico
google_analytics: UA-74368890-2
# baidu_analytics: e1043fa646166c95fc2fc95a9c5456f8
# copyright
copyright:
    enable: true
    author: shomy
    email: shomyliu@gmail.com
    site: http://shomy.top

# donate
donate:
  enable: false
  text: 欣赏此文？支持一下吧
