# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  About: /about
  rss: /atom.xml

menu_icon:
  Home: fa-home
  Archives: fa-archive
  Tag: fa-tag
  About: fa-user
  rss: fa-rss

# Content
excerpt_link: Read More

# Miscellaneous
favicon: /image/favicon.ico
google_analytics: UA-74368890-2
baidu_analytics: 32b891bf31961970a5392746b044d4e1
# copyright
copyright:
    enable: false
    author: shomoy
    email: shomyliu@gmail.com
    site: http://shomy.top

# donate
donate:
  enable: false
  text: 欣赏此文？支持一下吧
